version: '3.8'

services:
  postgres:
    container_name: finki-postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    container_name: finki-pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

  bot:
    container_name: finki-bot
    image: finki-discord-bot
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .env:/app/.env
      - ./config:/app/config
      - ./files:/app/files
      - ./sessions:/app/sessions
      - ./bot.log:/app/bot.log
      - .eslintcache:/app/.eslintcache
